default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['database_name'] %>
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_password'] %>

development:
  <<: *default
    port: 5432
    host: localhost

test:
  <<: *default
  database: test
  host: ''
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_password'] %>

production:
  <<: *default
  database: <%= ENV['database_production'] %>
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_password'] %>